In [82]:
%matplotlib inline
from ipywidgets import interactive
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [83]:
from sklearn import datasets
iris = datasets.load_iris()
data = pd.DataFrame(iris.data, columns = iris.feature_names)
y = iris.target

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size = 0.3)

In [85]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
gnb = GaussianNB()
mnb = MultinomialNB()
cmb = ComplementNB()

In [86]:
gnb.fit(X_train, y_train)
mnb.fit(X_train, y_train)
cmb.fit(X_train, y_train)

ComplementNB(alpha=1.0, class_prior=None, fit_prior=True, norm=False)

In [87]:
y_pred_gnb = gnb.predict(X_test)
y_pred_mnb = mnb.predict(X_test)
y_pred_cmb = mnb.predict(X_test)

In [88]:
from sklearn import metrics
gnb_accuracy = metrics.accuracy_score(y_test, y_pred_gnb)
print('Gaussian:', gnb_accuracy)
mnb_accuracy = metrics.accuracy_score(y_test, y_pred_mnb)
print('Multinomial:', mnb_accuracy)
mnb_accuracy = metrics.accuracy_score(y_test, y_pred_cmb)
print('ComplementNB:', mnb_accuracy)

Gaussian: 0.9333333333333333
Multinomial: 0.7555555555555555
ComplementNB: 0.7555555555555555


In [89]:
from sklearn.metrics import confusion_matrix
print('gnb')
print(confusion_matrix(y_test, y_pred_gnb))
print('mnb')
print(confusion_matrix(y_test, y_pred_mnb))
print('cmb')
print(confusion_matrix(y_test, y_pred_cmb))

gnb
[[12  0  0]
 [ 0 15  3]
 [ 0  0 15]]
mnb
[[12  0  0]
 [ 0  7 11]
 [ 0  0 15]]
cmb
[[12  0  0]
 [ 0  7 11]
 [ 0  0 15]]


In [93]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_gnb))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.83      0.91        18
           2       0.83      1.00      0.91        15

   micro avg       0.93      0.93      0.93        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.94      0.93      0.93        45

